name: Python 奕辅导签到
on:
  workflow_dispatch:
  schedule:
    - cron:  '5 16 * * *'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache python
      uses: actions/cache@v2
      env:
        cache-name: cache-py
      with:
        path: ./cache/cache.json
        key: ${{ runner.os }}-build-yfd-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-build-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip list
    - name: YFD Function
      run: |
        python YiFuDao_Puncher.py
    - uses: actions/upload-artifact@v2
      with:
        name: Upload Json
        path: ./cache/cache.json
